 export class Bookings{ 
    "bookings":[ 
       { 
          "id":10037,
          "slotId":1,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":14,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":2,
          "createdOn":"2019-12-24T15:29:48.000Z",
          "updatedOn":"2019-12-24T15:32:29.000Z",
          "slot":{ 
             "id":1,
             "startsAt":"2019-12-24T15:25:00.000Z",
             "duration":15,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Completed"
          },
          "appointments":[ 
             { 
                "id":1,
                "userId":5,
                "petId":1,
                "bookingId":10037,
                "notes":null,
                "createdOn":"2019-12-24T15:29:48.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10038,
          "slotId":2,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":13,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":3,
          "createdOn":"2019-12-24T15:35:29.000Z",
          "updatedOn":"2019-12-24T15:36:10.000Z",
          "slot":{ 
             "id":2,
             "startsAt":"2019-12-26T10:00:00.000Z",
             "duration":20,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Cancelled"
          },
          "appointments":[ 
             { 
                "id":2,
                "userId":5,
                "petId":1,
                "bookingId":10038,
                "notes":null,
                "createdOn":"2019-12-24T15:35:29.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10052,
          "slotId":2,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":13,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":10,
          "createdOn":"2019-12-24T16:22:49.000Z",
          "updatedOn":"2019-12-24T16:24:02.000Z",
          "slot":{ 
             "id":2,
             "startsAt":"2019-12-26T10:00:00.000Z",
             "duration":20,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Cancelled"
          },
          "appointments":[ 
             { 
                "id":9,
                "userId":5,
                "petId":2,
                "bookingId":10052,
                "notes":null,
                "createdOn":"2019-12-24T16:22:49.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10055,
          "slotId":2,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":13,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":11,
          "createdOn":"2019-12-24T16:57:24.000Z",
          "updatedOn":"2019-12-24T17:49:15.000Z",
          "slot":{ 
             "id":2,
             "startsAt":"2019-12-26T10:00:00.000Z",
             "duration":20,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Cancelled"
          },
          "appointments":[ 
             { 
                "id":10,
                "userId":5,
                "petId":1,
                "bookingId":10055,
                "notes":null,
                "createdOn":"2019-12-24T16:57:24.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10057,
          "slotId":10,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":14,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":12,
          "createdOn":"2019-12-24T19:15:29.000Z",
          "updatedOn":"2019-12-24T20:50:17.000Z",
          "slot":{ 
             "id":10,
             "startsAt":"2019-12-25T00:40:00.000Z",
             "duration":55,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":8,
                "firstName":"sachin",
                "email":"sachin.omprakash@lucidaogies.com"
             }
          },
          "status":{ 
             "statusName":"Completed"
          },
          "appointments":[ 
             { 
                "id":11,
                "userId":5,
                "petId":1,
                "bookingId":10057,
                "notes":null,
                "createdOn":"2019-12-24T19:15:29.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10058,
          "slotId":11,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":11,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":13,
          "createdOn":"2019-12-24T21:09:41.000Z",
          "updatedOn":"2019-12-25T12:59:39.000Z",
          "slot":{ 
             "id":11,
             "startsAt":"2019-12-26T02:00:00.000Z",
             "duration":55,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Confirmed"
          },
          "appointments":[ 
             { 
                "id":12,
                "userId":5,
                "petId":5,
                "bookingId":10058,
                "notes":null,
                "createdOn":"2019-12-24T21:09:41.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10060,
          "slotId":14,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":11,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":14,
          "createdOn":"2019-12-24T22:16:17.000Z",
          "updatedOn":"2019-12-25T12:59:49.000Z",
          "slot":{ 
             "id":14,
             "startsAt":"2019-12-26T04:30:00.000Z",
             "duration":40,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":15,
                "firstName":"gana",
                "email":"ganashree1295@gmail.com"
             }
          },
          "status":{ 
             "statusName":"Confirmed"
          },
          "appointments":[ 
             { 
                "id":13,
                "userId":5,
                "petId":7,
                "bookingId":10060,
                "notes":null,
                "createdOn":"2019-12-24T22:16:17.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10062,
          "slotId":25,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":13,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":23,
          "createdOn":"2019-12-25T15:40:23.000Z",
          "updatedOn":"2019-12-25T21:48:22.000Z",
          "slot":{ 
             "id":25,
             "startsAt":"2019-12-27T04:00:00.000Z",
             "duration":15,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Cancelled"
          },
          "appointments":[ 
             { 
                "id":14,
                "userId":5,
                "petId":8,
                "bookingId":10062,
                "notes":null,
                "createdOn":"2019-12-25T15:40:23.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10063,
          "slotId":31,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":13,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":24,
          "createdOn":"2019-12-25T21:42:02.000Z",
          "updatedOn":"2019-12-25T21:49:49.000Z",
          "slot":{ 
             "id":31,
             "startsAt":"2019-12-26T10:30:00.000Z",
             "duration":30,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":49,
                "firstName":"Prithvi",
                "email":"reachprithvi@gmail.com"
             }
          },
          "status":{ 
             "statusName":"Cancelled"
          },
          "appointments":[ 
             { 
                "id":15,
                "userId":5,
                "petId":7,
                "bookingId":10063,
                "notes":null,
                "createdOn":"2019-12-25T21:42:02.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10064,
          "slotId":25,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":13,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":25,
          "createdOn":"2019-12-26T05:22:46.000Z",
          "updatedOn":"2019-12-26T05:23:30.000Z",
          "slot":{ 
             "id":25,
             "startsAt":"2019-12-27T04:00:00.000Z",
             "duration":15,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Cancelled"
          },
          "appointments":[ 
             { 
                "id":16,
                "userId":5,
                "petId":7,
                "bookingId":10064,
                "notes":null,
                "createdOn":"2019-12-26T05:22:46.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10065,
          "slotId":25,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":11,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":26,
          "createdOn":"2019-12-26T05:24:34.000Z",
          "updatedOn":"2019-12-26T10:44:29.000Z",
          "slot":{ 
             "id":25,
             "startsAt":"2019-12-27T04:00:00.000Z",
             "duration":15,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Confirmed"
          },
          "appointments":[ 
             { 
                "id":17,
                "userId":5,
                "petId":7,
                "bookingId":10065,
                "notes":null,
                "createdOn":"2019-12-26T05:24:34.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10071,
          "slotId":36,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":13,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":37,
          "createdOn":"2019-12-26T10:10:34.000Z",
          "updatedOn":"2019-12-26T12:09:27.000Z",
          "slot":{ 
             "id":36,
             "startsAt":"2019-12-27T06:53:00.000Z",
             "duration":15,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":49,
                "firstName":"Prithvi",
                "email":"reachprithvi@gmail.com"
             }
          },
          "status":{ 
             "statusName":"Cancelled"
          },
          "appointments":[ 
             { 
                "id":23,
                "userId":5,
                "petId":7,
                "bookingId":10071,
                "notes":null,
                "createdOn":"2019-12-26T10:10:34.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10073,
          "slotId":51,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":11,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":38,
          "createdOn":"2019-12-26T10:35:23.000Z",
          "updatedOn":"2019-12-27T05:36:48.000Z",
          "slot":{ 
             "id":51,
             "startsAt":"2019-12-27T07:00:00.000Z",
             "duration":20,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Confirmed"
          },
          "appointments":[ 
             { 
                "id":24,
                "userId":5,
                "petId":7,
                "bookingId":10073,
                "notes":null,
                "createdOn":"2019-12-26T10:35:23.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       },
       { 
          "id":10078,
          "slotId":49,
          "userId":5,
          "practiceAppointmentTypeId":1,
          "statusId":10,
          "cancelNotes":null,
          "vsBookingId":null,
          "userRating":null,
          "practiceRating":null,
          "bookingTransactionId":47,
          "createdOn":"2019-12-26T14:35:44.000Z",
          "updatedOn":null,
          "slot":{ 
             "id":49,
             "startsAt":"2019-12-27T09:30:00.000Z",
             "duration":20,
             "isPrivate":false,
             "practice":{ 
                "id":3,
                "practiceName":"Lucida clinic "
             },
             "user":{ 
                "id":4,
                "firstName":"Chetan KV",
                "email":"chethan.kv@agkiya.cloud"
             }
          },
          "status":{ 
             "statusName":"Awaiting Confirmation"
          },
          "appointments":[ 
             { 
                "id":26,
                "userId":5,
                "petId":19,
                "bookingId":10078,
                "notes":null,
                "createdOn":"2019-12-26T14:35:44.000Z"
             }
          ],
          "practiceAppointmentType":{ 
             "appointmentType":"General Checkup",
             "customerFee":20
          }
       }
    ]
 }